# Generated by Django 2.2 on 2021-02-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_admin', '0003_quiz_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
