# Generated by Django 2.2 on 2021-02-20 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_admin', '0005_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_question', to='quiz_admin.Quiz'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_by',
            field=models.CharField(max_length=255),
        ),
    ]
